const fr={
name:'Français',
dict:{
'importPng':'Importer PNG',
'info.default':'PNG indexé, 16 couleurs max, dimensions multiples de 8px.',
'badge.none':'aucun fichier',
'badge.reading':'lecture',
'badge.error':'erreur',
'badge.overflow':'dépassement',
'badge.warning':'attention',
'badge.valid':'valide',
'sec.tiles':'Tiles',
'startValue':'Valeur de départ',
'maxBudget':'Budget maximum',
'dedupe':'Retirer les doublons',
'mirror':'Retirer miroirs H/V/HV',
'sec.export':'Exportation',
'sec.stats':'Statistiques',
'stats.tilesSource':'Tiles source',
'stats.tilesValid':'Tiles valides',
'stats.tilesRemoved':'Tiles retirées',
'stats.tilesBin':'Tiles (BIN)',
'stats.tilesPsg':'Tiles (PSG)',
'stats.tilesZx7':'Tiles (ZX7)',
'sec.tilemap':'Tilemap',
'palette2':'Palette 2',
'priority':'1er plan',
'orderBy':'Ordonner par',
'order.rowsTop':'ligne (Haut en Bas) (défaut)',
'order.rowsBottom':'ligne (Bas en Haut)',
'order.colsLeft':'colonne (Gauche à Droite)',
'order.colsRight':'colonne (Droite à Gauche)',
'sec.exportTilemap':'Exportation Tilemap',
'stats.tilemapBin':'Tilemap (BIN)',
'stats.tilemapRle':'Tilemap (RLE)',
'stats.tilemapStm':'Tilemap (STM)',
'empty.noPng':'Aucun PNG chargé',
'empty.importPng':'Importer un PNG',
'sec.shelf':'Chutier',
'btn.reorder':'Réorganiser',
'btn.edit':'Editer',
'btn.modify':'Modifier',
'btn.import':'Importer',
'btn.default':'Par défaut',
'btn.addVariant':'Ajouter une variante',
'btn.done':'Terminé',
'btn.cancel':'Annuler',
'btn.close':'Fermer',
'btn.quit':'Quitter',
'sec.edit':'Edition',
'edit.info':'Choisir une couleur dans la palette, puis peindre les pixels.',
'edit.colorEmpty':'Couleur —',
'empty.tiles':'Les tiles valides apparaîtront ici après import.',
'sec.palette':'Palette',
'empty.palette':'Les couleurs utilisées apparaîtront ici après import.',
'export.png':'⬇ PNG',
'export.bin':'⬇ BIN',
'export.psg':'⬇ PSG',
'export.zx7':'⬇ ZX7',
'export.tsx':'⬇ TSX',
'export.asm':'⬇ ASM',
'export.rle':'⬇ RLE',
'export.stm':'⬇ STM',
'export.tmx':'⬇ TMX',
'export.act':'⬇ ACT',
'export.gpl':'⬇ GPL',
'export.c':'⬇ C',
'export.jasc':'⬇ JASC',
'picker.title':'Modifier couleur',
'png.err.indexed':'PNG invalide : le fichier doit être indexé (color type 3).',
'png.err.plte':'PNG invalide : palette PLTE absente.',
'png.err.colors':'PNG invalide : palette supérieure à 16 couleurs.',
'png.err.size':'PNG invalide : largeur et hauteur doivent être multiples de 8px.',
'toast.pngImported':'PNG importé',
'toast.tilesReorderOn':'Réorganisation tiles activée',
'toast.tilesReorderOff':'Réorganisation tiles désactivée',
'toast.paletteReorderOn':'Réorganisation palette activée',
'toast.paletteReorderOff':'Réorganisation palette désactivée',
'toast.paletteEditOn':'Modification palette activée',
'toast.paletteEditOff':'Modification palette désactivée',
'toast.tileEditOn':'Edition tile activée : cliquer un tile du chutier',
'toast.tileEditOff':'Edition tile désactivée',
'toast.tileEditing':'Edition tile {idx}',
'toast.tileMerged':'Tile fusionnée avec un tile existant',
'toast.tileModified':'Tile modifiée',
'toast.editCanceled':'Edition annulée',
'toast.colorSelected':'Couleur {idx} sélectionnée',
'toast.tileMoved':'Tile déplacée',
'toast.colorMoved':'Couleur déplacée',
'toast.colorChanged':'Couleur modifiée : SMS ${sms}',
'toast.paletteActive':'Palette active : {name}',
'toast.paletteRemoved':'Palette supprimée',
'toast.paletteRestored':'Palette d’origine restaurée',
'toast.paletteImported':'Palette importée : {n} couleur{s}',
'toast.paletteVariantAdded':'Variante ajoutée et activée : {n} couleur{s}',
'toast.psgMissing':'Compresseur PSG absent',
'toast.zx7Missing':'Compresseur ZX7 absent',
'err.paletteEmpty':'Palette importée vide ou non reconnue.',
'stats.budgetTitle':'Budget dépassé : {valid}/{budget} tiles (+{excess})',
'hud.source':'{w}×{h}px • {raw} tiles source',
'hud.tiles':'{valid} tiles{budget} • {kb} kB{tilemap}',
'hud.budget':' • ⚠ budget +{excess}',
'hud.tilemap':' • tilemap {w}×{h}',
'file.meta':'{file} — {w}×{h}px — {colors} couleurs',
'file.overflow':'Trop de tiles : {valid} tiles pour une valeur de départ {start} (max {max}).{budget}',
'file.budget':' ⚠ Budget dépassé : {valid}/{budget} (+{excess})',
'file.removed':' • {removed} retirée{s}',
'file.warn':' • ⚠ budget dépassé : {valid}/{budget} (+{excess})',
'file.tiles':'{info} • {raw} source → {valid} tiles{warn}{removed}{tilemap} • {colors} couleurs utilisées{palette} • {kb} kB{reorder}{edit}{mod}{palMode}',
'file.reorder':' • réorganisation tiles active',
'file.edit':' • édition tile active',
'file.modifiedPalette':' • palette modifiée',
'file.paletteReorder':' • réorganisation palette active',
'file.paletteEdit':' • modification palette active',
'file.paletteNum':' • palette {current}/{total}',
'edit.color':'Couleur {idx} — {hex} — SMS ${sms}',
'edit.tileInfo':'Tile {idx} — cliquer/glisser pour peindre. La palette sert uniquement au choix de couleur.',
'tip.tile':'ID {id} ({hex})\nIndex chutier {idx}\nOccurrences {occ}\nEmplacement {x},{y}px\nTile source {tx},{ty}{more}',
'tip.more':'\n{occ} emplacements surlignés',
'tip.dragTile':'Déplacer tile\nID actuel {old} ({oldHex})\nNouvel ID {new} ({newHex})\nPosition {from} → {to}',
'tip.palette':'Index {idx}\nIndex PNG {png}\nHEX {hex}\nSMS ${sms} ({r},{g},{b})\nOccurrences {occ}',
'tip.dragColor':'Déplacer couleur\nIndex actuel {from}\nNouvel index {to}\nPNG {png}\nSMS ${sms}',
'picker.titleFull':'Modifier couleur — index {idx} / PNG {png}',
'picker.current':'Actuelle {hex} — SMS ${sms} ({r},{g},{b})',
'picker.origin':'Origine {hex}',
'picker.smsTitle':'${sms} — RGB222 {r},{g},{b}',
'variant.defaultName':'Palette {idx}',
'variant.remove':'Supprimer',
'variant.new':'Variante {idx}',
'choice.cancel':'Annuler',
'choice.tsxTitle':'Export TSX',
'choice.tsxZip':'ZIP + PNG',
'choice.tsxSingle':'TSX seul',
'choice.tmxTitle':'Export TMX',
'choice.tmxZip':'ZIP + TMX/TSX/PNG',
'choice.tmxSingle':'TMX seul',
'export.paletteAsmComment':'; {name} palette — Master System RGB222',
'util.png.invalid':'Fichier PNG invalide.',
'util.png.truncated':'PNG tronqué.',
'util.png.pixelMismatch':'PNG invalide : certains pixels ne correspondent pas à la palette indexée.',
'util.pal.pngUnavailable':'Import PNG palette indisponible.',
'util.pal.pngIndexed':'PNG palette invalide : le fichier doit être indexé.',
'util.pal.pngPlte':'PNG palette invalide : PLTE absent.',
'util.pal.binRange':'BIN invalide : valeur supérieure à $3F.',
'util.pal.asmRange':'ASM invalide : valeur supérieure à $3F.',
'util.psg.tooMany':'Trop de tiles (>65535)',
'asm.order.rowsTop':'ligne (haut -> bas)',
'asm.order.rowsBottom':'ligne (bas -> haut)',
'asm.order.colsLeft':'colonne (gauche -> droite)',
'asm.order.colsRight':'colonne (droite -> gauche)',
'asm.yes':'oui',
'asm.no':'non',
'asm.title':'; {name} tilemap — Master System',
'asm.dim':'; Dimensions : {w}×{h} tiles',
'asm.order':'; Ordre : {order}',
'asm.start':'; Valeur de départ tiles : {start}',
'asm.dedupe':'; Déduplication tiles : {value}',
'asm.mirror':'; Détection miroirs H/V/HV : {value}',
'asm.palette2':'; Palette 2 : {value} (+$0800)',
'asm.priority':'; 1er plan : {value} (+$1000)',
'palette.mode':'Mode',
'palette.mode.sms':'Master System',
'palette.mode.gg':'Game Gear',
'edit.colorSms':'Couleur {idx} — {hex} — SMS ${sms} ({r},{g},{b})',
'edit.colorGg':'Couleur {idx} — {hex} — GG ${gg} ({r},{g},{b})',
'tip.paletteSms':'Index {idx}\nIndex PNG {png}\nHEX {hex}\nSMS ${sms} ({r},{g},{b})\nOccurrences {occ}',
'tip.paletteGg':'Index {idx}\nIndex PNG {png}\nHEX {hex}\nGG ${gg} ({r},{g},{b})\nOccurrences {occ}',
'tip.dragColorSms':'Déplacer couleur\nIndex actuel {from}\nNouvel index {to}\nPNG {png}\nSMS ${sms}',
'tip.dragColorGg':'Déplacer couleur\nIndex actuel {from}\nNouvel index {to}\nPNG {png}\nGG ${gg}',
'picker.currentSms':'Actuelle {hex} — SMS ${sms} ({r},{g},{b})',
'picker.currentGg':'Actuelle {hex} — GG ${gg} ({r},{g},{b})',
'picker.ggRgb':'RGB444',
'picker.eyedropper':'Pipette',
'toast.colorChangedSms':'Couleur modifiée : SMS ${sms}',
'toast.colorChangedGg':'Couleur modifiée : GG ${gg}',
'toast.paletteMode':'Mode palette : {mode}',
'err.eyedropper':'Pipette indisponible dans ce navigateur.',
'util.pal.ggRange':'Palette GG invalide : valeur supérieure à $0FFF.',
'export.paletteAsmCommentSms':'; {name} palette — Master System RGB222',
'export.paletteAsmCommentGg':'; {name} palette — Game Gear RGB444',
'tmx.prop.palette2':'Palette 2 Master System',
'tmx.prop.priority':'Priorité / 1er plan Master System'
}
};
window.TileLangPacks=window.TileLangPacks||{};
window.TileLangPacks.fr=fr;
