const en={
name:'English',
dict:{
'importPng':'Import PNG',
'info.default':'Indexed PNG, max 16 colors, dimensions multiple of 8px.',
'badge.none':'no file',
'badge.reading':'reading',
'badge.error':'error',
'badge.overflow':'overflow',
'badge.warning':'warning',
'badge.valid':'valid',
'sec.tiles':'Tiles',
'startValue':'Start value',
'maxBudget':'Maximum budget',
'dedupe':'Remove duplicates',
'mirror':'Remove H/V/HV mirrors',
'sec.export':'Export',
'sec.stats':'Statistics',
'stats.tilesSource':'Source tiles',
'stats.tilesValid':'Valid tiles',
'stats.tilesRemoved':'Removed tiles',
'stats.tilesBin':'Tiles (BIN)',
'stats.tilesPsg':'Tiles (PSG)',
'stats.tilesZx7':'Tiles (ZX7)',
'sec.tilemap':'Tilemap',
'palette2':'Palette 2',
'priority':'Priority',
'orderBy':'Order by',
'order.rowsTop':'row (Top to Bottom) (default)',
'order.rowsBottom':'row (Bottom to Top)',
'order.colsLeft':'column (Left to Right)',
'order.colsRight':'column (Right to Left)',
'sec.exportTilemap':'Tilemap Export',
'stats.tilemapBin':'Tilemap (BIN)',
'stats.tilemapRle':'Tilemap (RLE)',
'stats.tilemapStm':'Tilemap (STM)',
'empty.noPng':'No PNG loaded',
'empty.importPng':'Import a PNG',
'sec.shelf':'Tile shelf',
'btn.reorder':'Reorder',
'btn.edit':'Edit',
'btn.modify':'Modify',
'btn.import':'Import',
'btn.default':'Default',
'btn.addVariant':'Add variant',
'btn.done':'Done',
'btn.cancel':'Cancel',
'btn.close':'Close',
'btn.quit':'Quit',
'sec.edit':'Edit',
'edit.info':'Choose a color in the palette, then paint pixels.',
'edit.colorEmpty':'Color —',
'empty.tiles':'Valid tiles will appear here after import.',
'sec.palette':'Palette',
'empty.palette':'Used colors will appear here after import.',
'export.png':'⬇ PNG',
'export.bin':'⬇ BIN',
'export.psg':'⬇ PSG',
'export.zx7':'⬇ ZX7',
'export.tsx':'⬇ TSX',
'export.asm':'⬇ ASM',
'export.rle':'⬇ RLE',
'export.stm':'⬇ STM',
'export.tmx':'⬇ TMX',
'export.act':'⬇ ACT',
'export.gpl':'⬇ GPL',
'export.c':'⬇ C',
'export.jasc':'⬇ JASC',
'picker.title':'Modify color',
'png.err.indexed':'Invalid PNG: file must be indexed (color type 3).',
'png.err.plte':'Invalid PNG: missing PLTE palette.',
'png.err.colors':'Invalid PNG: palette has more than 16 colors.',
'png.err.size':'Invalid PNG: width and height must be multiples of 8px.',
'toast.pngImported':'PNG imported',
'toast.tilesReorderOn':'Tile reordering enabled',
'toast.tilesReorderOff':'Tile reordering disabled',
'toast.paletteReorderOn':'Palette reordering enabled',
'toast.paletteReorderOff':'Palette reordering disabled',
'toast.paletteEditOn':'Palette editing enabled',
'toast.paletteEditOff':'Palette editing disabled',
'toast.tileEditOn':'Tile editing enabled: click a tile in the shelf',
'toast.tileEditOff':'Tile editing disabled',
'toast.tileEditing':'Editing tile {idx}',
'toast.tileMerged':'Tile merged with an existing tile',
'toast.tileModified':'Tile modified',
'toast.editCanceled':'Edit canceled',
'toast.colorSelected':'Color {idx} selected',
'toast.tileMoved':'Tile moved',
'toast.colorMoved':'Color moved',
'toast.colorChanged':'Color modified: SMS ${sms}',
'toast.paletteActive':'Active palette: {name}',
'toast.paletteRemoved':'Palette removed',
'toast.paletteRestored':'Original palette restored',
'toast.paletteImported':'Palette imported: {n} color{s}',
'toast.paletteVariantAdded':'Variant added and enabled: {n} color{s}',
'toast.psgMissing':'PSG compressor missing',
'toast.zx7Missing':'ZX7 compressor missing',
'err.paletteEmpty':'Imported palette is empty or not recognized.',
'stats.budgetTitle':'Budget exceeded: {valid}/{budget} tiles (+{excess})',
'hud.source':'{w}×{h}px • {raw} source tiles',
'hud.tiles':'{valid} tiles{budget} • {kb} kB{tilemap}',
'hud.budget':' • ⚠ budget +{excess}',
'hud.tilemap':' • tilemap {w}×{h}',
'file.meta':'{file} — {w}×{h}px — {colors} colors',
'file.overflow':'Too many tiles: {valid} tiles for start value {start} (max {max}).{budget}',
'file.budget':' ⚠ Budget exceeded: {valid}/{budget} (+{excess})',
'file.removed':' • {removed} removed',
'file.warn':' • ⚠ budget exceeded: {valid}/{budget} (+{excess})',
'file.tiles':'{info} • {raw} source → {valid} tiles{warn}{removed}{tilemap} • {colors} used colors{palette} • {kb} kB{reorder}{edit}{mod}{palMode}',
'file.reorder':' • tile reordering enabled',
'file.edit':' • tile editing enabled',
'file.modifiedPalette':' • palette modified',
'file.paletteReorder':' • palette reordering enabled',
'file.paletteEdit':' • palette editing enabled',
'file.paletteNum':' • palette {current}/{total}',
'edit.color':'Color {idx} — {hex} — SMS ${sms}',
'edit.tileInfo':'Tile {idx} — click/drag to paint. The palette is only used to choose the color.',
'tip.tile':'ID {id} ({hex})\nShelf index {idx}\nOccurrences {occ}\nPosition {x},{y}px\nSource tile {tx},{ty}{more}',
'tip.more':'\n{occ} highlighted positions',
'tip.dragTile':'Move tile\nCurrent ID {old} ({oldHex})\nNew ID {new} ({newHex})\nPosition {from} → {to}',
'tip.palette':'Index {idx}\nPNG index {png}\nHEX {hex}\nSMS ${sms} ({r},{g},{b})\nOccurrences {occ}',
'tip.dragColor':'Move color\nCurrent index {from}\nNew index {to}\nPNG {png}\nSMS ${sms}',
'picker.titleFull':'Modify color — index {idx} / PNG {png}',
'picker.current':'Current {hex} — SMS ${sms} ({r},{g},{b})',
'picker.origin':'Origin {hex}',
'picker.smsTitle':'${sms} — RGB222 {r},{g},{b}',
'variant.defaultName':'Palette {idx}',
'variant.remove':'Remove',
'variant.new':'Variant {idx}',
'choice.cancel':'Cancel',
'choice.tsxTitle':'Export TSX',
'choice.tsxZip':'ZIP + PNG',
'choice.tsxSingle':'TSX only',
'choice.tmxTitle':'Export TMX',
'choice.tmxZip':'ZIP + TMX/TSX/PNG',
'choice.tmxSingle':'TMX only',
'export.paletteAsmComment':'; {name} palette — Master System RGB222',
'util.png.invalid':'Invalid PNG file.',
'util.png.truncated':'Truncated PNG.',
'util.png.pixelMismatch':'Invalid PNG: some pixels do not match the indexed palette.',
'util.pal.pngUnavailable':'PNG palette import unavailable.',
'util.pal.pngIndexed':'Invalid palette PNG: file must be indexed.',
'util.pal.pngPlte':'Invalid palette PNG: missing PLTE.',
'util.pal.binRange':'Invalid BIN: value greater than $3F.',
'util.pal.asmRange':'Invalid ASM: value greater than $3F.',
'util.psg.tooMany':'Too many tiles (>65535)',
'asm.order.rowsTop':'row (top -> bottom)',
'asm.order.rowsBottom':'row (bottom -> top)',
'asm.order.colsLeft':'column (left -> right)',
'asm.order.colsRight':'column (right -> left)',
'asm.yes':'yes',
'asm.no':'no',
'asm.title':'; {name} tilemap — Master System',
'asm.dim':'; Dimensions: {w}×{h} tiles',
'asm.order':'; Order: {order}',
'asm.start':'; Tile start value: {start}',
'asm.dedupe':'; Tile deduplication: {value}',
'asm.mirror':'; H/V/HV mirror detection: {value}',
'asm.palette2':'; Palette 2: {value} (+$0800)',
'asm.priority':'; Priority: {value} (+$1000)',
'palette.mode':'Mode',
'palette.mode.sms':'Master System',
'palette.mode.gg':'Game Gear',
'edit.colorSms':'Color {idx} — {hex} — SMS ${sms} ({r},{g},{b})',
'edit.colorGg':'Color {idx} — {hex} — GG ${gg} ({r},{g},{b})',
'tip.paletteSms':'Index {idx}\nPNG index {png}\nHEX {hex}\nSMS ${sms} ({r},{g},{b})\nOccurrences {occ}',
'tip.paletteGg':'Index {idx}\nPNG index {png}\nHEX {hex}\nGG ${gg} ({r},{g},{b})\nOccurrences {occ}',
'tip.dragColorSms':'Move color\nCurrent index {from}\nNew index {to}\nPNG {png}\nSMS ${sms}',
'tip.dragColorGg':'Move color\nCurrent index {from}\nNew index {to}\nPNG {png}\nGG ${gg}',
'picker.currentSms':'Current {hex} — SMS ${sms} ({r},{g},{b})',
'picker.currentGg':'Current {hex} — GG ${gg} ({r},{g},{b})',
'picker.ggRgb':'RGB444',
'picker.eyedropper':'Eyedropper',
'toast.colorChangedSms':'Color changed: SMS ${sms}',
'toast.colorChangedGg':'Color changed: GG ${gg}',
'toast.paletteMode':'Palette mode: {mode}',
'err.eyedropper':'Eyedropper unavailable in this browser.',
'util.pal.ggRange':'Invalid GG palette: value greater than $0FFF.',
'export.paletteAsmCommentSms':'; {name} palette — Master System RGB222',
'export.paletteAsmCommentGg':'; {name} palette — Game Gear RGB444',
'tmx.prop.palette2':'Master System Palette 2',
'tmx.prop.priority':'Master System priority / foreground'
}
};
window.TileLangPacks=window.TileLangPacks||{};
window.TileLangPacks.en=en;
